name: tap_hero
description: Tap Hero

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.1.0
  share_plus: ^10.1.2
  simple_animations: ^5.1.0
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.0

# dart run icons_launcher:create
icons_launcher:
  image_path: "assets/app_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/background/
    - assets/character/
    - assets/boss/
    - assets/elements/
    - assets/audio/

  fonts:
    - family: Gameplay
      fonts:
        - asset: fonts/gameplay.ttf
